[package]
name = "memflow-win32"
version = "0.1.5"
authors = ["ko1N <ko1N1337@gmail.com>", "Aurimas Blažulionis <0x60@pm.me>"]
edition = "2018"
description = "win32 integration of the memflow physical memory introspection framework"
documentation = "https://docs.rs/memflow-win32"
readme = "README.md"
homepage = "https://memflow.github.io"
repository = "https://github.com/memflow/memflow"
license-file = "../LICENSE"
keywords = [ "memflow", "introspection", "memory", "dma" ]
categories = [ "api-bindings", "memory-management", "os" ]

[badges]
maintenance = { status = "actively-developed" }
codecov = { repository = "github", branch = "master", service = "github" }

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
memflow = { version = "0.1", path = "../memflow", default-features = false }
log = { version = "0.4", default-features = false }
pelite = { version = "0.9", default-features = false }
goblin = { version = "0.4", default-features = false, features = ["pe32", "pe64"] }
widestring = { version = "0.4", default-features = false, features = ["alloc"] }
no-std-compat = { version = "0.4", features = ["alloc"] }
serde = { version = "1.0", default-features = false, optional = true, features = ["derive"] }
simple_logger = { version = "1.11.0", optional = true }

# will be replaced by our own signature scanner
regex = { version = "1", optional = true }

# symbolstore
dirs = { version = "3.0", optional = true }
ureq = { version = "2.1", optional = true }
pdb = { version = "0.7", optional = true }
pbr = { version = "1.0", optional = true }
progress-streams = { version = "1.1", optional = true }

[dev_dependencies]
simple_logger = "1.0"
rand = "0.8"
rand_xorshift = "0.3"
clap = "2.33"
toml = "0.5"

[build_dependencies]
toml = "0.5"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
memflow = { version = "0.1", path = "../memflow", default-features = false }

[features]
default = ["std", "serde_derive", "embed_offsets", "symstore", "download_progress", "regex"]
std = ["no-std-compat/std", "memflow/std", "pelite/std", "goblin/std"]
plugins = ["memflow/plugins", "simple_logger"]
embed_offsets = ["serde", "memflow/serde_derive"]
serde_derive = ["serde", "memflow/serde_derive", "pelite/std", "pelite/serde", "goblin/std"]
symstore = ["dirs", "ureq", "pdb"]
download_progress = ["pbr", "progress-streams"]

[[example]]
name = "dump_offsets"
path = "examples/dump_offsets.rs"

[[example]]
name = "generate_offsets"
path = "examples/generate_offsets.rs"
